const fs = require('node:fs');
const path = require('node:path');

const dbRoot = path.resolve(__dirname, '..');
const sharedSchema = fs.readFileSync(path.join(dbRoot, 'prisma', 'schema.prisma'), 'utf8');
const sqliteSchema = `// This file is automatically generated. DO NOT EDIT.\n\ndatasource db {\n  provider = "sqlite"\n  url      = env("DATABASE_FILE")\n}\n\ngenerator client {\n  provider = "prisma-client-js"\n  output   = "../generated/sqlite"\n}\n`;

fs.mkdirSync(path.join(dbRoot, 'dialects', 'sqlite'), { recursive: true });
fs.writeFileSync(path.join(dbRoot, 'dialects', 'sqlite', 'sqlite.schema.prisma'), `${sqliteSchema}\n${sharedSchema}`);
console.log('Generated schema files for SQLite');
