import { execFile } from 'node:child_process';
import { chmod, mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { promisify } from 'node:util';
import { describe, expect, it } from 'vitest';

const execFileAsync = promisify(execFile);

describe('plugin runtime apply script', () => {
  it('starts stopped autostart plugin programs from the generated supervisor config after update', async () => {
    const tempRoot = await mkdtemp(join(tmpdir(), 'vd-plugin-runtime-apply-starts-'));
    const binDir = join(tempRoot, 'bin');
    const supervisorConfigDir = join(tempRoot, 'supervisor');
    const statusPath = join(tempRoot, 'supervisor-status');
    const callsPath = join(tempRoot, 'supervisor-calls');
    await mkdir(binDir);
    await mkdir(supervisorConfigDir);
    await writeFile(join(supervisorConfigDir, 'vd-plugin--vd_beads_web--web.conf'), [
      '; generated by VD plugin service orchestrator for vd.beads-web@v0.11.6 service web',
      '[program:vd-plugin--vd_beads_web--web]',
      'command=/var/lib/vd/plugins/vd.beads-web/v0.11.6/extracted/bin/beads-web',
      'autostart=true',
      '',
    ].join('\n'));
    await writeFile(join(supervisorConfigDir, 'vd-plugin--manual--worker.conf'), [
      '; generated by VD plugin service orchestrator for vd.manual@v1 service worker',
      '[program:vd-plugin--manual--worker]',
      'command=/bin/true',
      'autostart=false',
      '',
    ].join('\n'));
    await writeFile(statusPath, 'STOPPED');
    await writeExecutable(join(binDir, 'node'), '#!/bin/sh\nexit 0\n');
    await writeExecutable(join(binDir, 'caddy'), '#!/bin/sh\nexit 0\n');
    await writeFakeSupervisorctl(binDir, statusPath, callsPath);

    await execFileAsync('sh', [resolve(process.cwd(), 'plugins/scripts/vd-plugin-runtime-apply.sh')], {
      env: {
        ...process.env,
        PATH: `${binDir}:${process.env.PATH ?? ''}`,
        VD_PLUGIN_SUPERVISOR_CONFIG_DIR: supervisorConfigDir,
      },
    });

    await expect(readFile(statusPath, 'utf8')).resolves.toBe('RUNNING\n');
    await expect(readFile(callsPath, 'utf8')).resolves.toContain('start vd-plugin--vd_beads_web--web');
    await expect(readFile(callsPath, 'utf8')).resolves.not.toContain('start vd-plugin--manual--worker');
  });

  it('starts stopped autostart plugin programs even when supervisor status exits non-zero', async () => {
    const tempRoot = await mkdtemp(join(tmpdir(), 'vd-plugin-runtime-apply-starts-nonzero-status-'));
    const binDir = join(tempRoot, 'bin');
    const supervisorConfigDir = join(tempRoot, 'supervisor');
    const statusPath = join(tempRoot, 'supervisor-status');
    const callsPath = join(tempRoot, 'supervisor-calls');
    await mkdir(binDir);
    await mkdir(supervisorConfigDir);
    await writeFile(join(supervisorConfigDir, 'vd-plugin--vd_beads_web--web.conf'), [
      '; generated by VD plugin service orchestrator for vd.beads-web@v0.11.6 service web',
      '[program:vd-plugin--vd_beads_web--web]',
      'command=/var/lib/vd/plugins/vd.beads-web/v0.11.6/extracted/bin/beads-web',
      'autostart=true',
      '',
    ].join('\n'));
    await writeFile(statusPath, 'STOPPED');
    await writeExecutable(join(binDir, 'node'), '#!/bin/sh\nexit 0\n');
    await writeExecutable(join(binDir, 'caddy'), '#!/bin/sh\nexit 0\n');
    await writeFakeSupervisorctl(binDir, statusPath, callsPath, { nonZeroStatuses: ['STOPPED'] });

    await execFileAsync('sh', [resolve(process.cwd(), 'plugins/scripts/vd-plugin-runtime-apply.sh')], {
      env: {
        ...process.env,
        PATH: `${binDir}:${process.env.PATH ?? ''}`,
        VD_PLUGIN_SUPERVISOR_CONFIG_DIR: supervisorConfigDir,
      },
    });

    await expect(readFile(statusPath, 'utf8')).resolves.toBe('RUNNING\n');
    await expect(readFile(callsPath, 'utf8')).resolves.toContain('status vd-plugin--vd_beads_web--web');
    await expect(readFile(callsPath, 'utf8')).resolves.toContain('start vd-plugin--vd_beads_web--web');
  });

  it('fails with an actionable error when supervisor status output is not parseable', async () => {
    const tempRoot = await mkdtemp(join(tmpdir(), 'vd-plugin-runtime-apply-unparseable-status-'));
    const binDir = join(tempRoot, 'bin');
    const supervisorConfigDir = join(tempRoot, 'supervisor');
    await mkdir(binDir);
    await mkdir(supervisorConfigDir);
    await writeFile(join(supervisorConfigDir, 'vd-plugin--vd_broken--web.conf'), [
      '; generated by VD plugin service orchestrator for vd.broken@v1 service web',
      '[program:vd-plugin--vd_broken--web]',
      'command=/bin/false',
      'autostart=true',
      '',
    ].join('\n'));
    await writeExecutable(join(binDir, 'node'), '#!/bin/sh\nexit 0\n');
    await writeExecutable(join(binDir, 'caddy'), '#!/bin/sh\nexit 0\n');
    await writeExecutable(join(binDir, 'supervisorctl'), `#!/bin/sh
case "$1" in
  reread|update)
    exit 0
    ;;
  status)
    exit 3
    ;;
esac
exit 1
`);

    await expect(execFileAsync('sh', [resolve(process.cwd(), 'plugins/scripts/vd-plugin-runtime-apply.sh')], {
      env: {
        ...process.env,
        PATH: `${binDir}:${process.env.PATH ?? ''}`,
        VD_PLUGIN_SUPERVISOR_CONFIG_DIR: supervisorConfigDir,
      },
    })).rejects.toMatchObject({
      stderr: expect.stringContaining('Failed to read supervisor status for enabled plugin program vd-plugin--vd_broken--web'),
    });
  });

  it('waits for already-starting enabled plugin programs instead of issuing a duplicate start', async () => {
    const tempRoot = await mkdtemp(join(tmpdir(), 'vd-plugin-runtime-apply-waits-'));
    const binDir = join(tempRoot, 'bin');
    const supervisorConfigDir = join(tempRoot, 'supervisor');
    const statusPath = join(tempRoot, 'supervisor-status');
    const callsPath = join(tempRoot, 'supervisor-calls');
    await mkdir(binDir);
    await mkdir(supervisorConfigDir);
    await writeFile(join(supervisorConfigDir, 'vd-plugin--vd_beads_web--web.conf'), [
      '; generated by VD plugin service orchestrator for vd.beads-web@v0.11.6 service web',
      '[program:vd-plugin--vd_beads_web--web]',
      'command=/var/lib/vd/plugins/vd.beads-web/v0.11.6/extracted/bin/beads-web',
      'autostart=true',
      '',
    ].join('\n'));
    await writeFile(statusPath, 'STARTING');
    await writeExecutable(join(binDir, 'node'), '#!/bin/sh\nexit 0\n');
    await writeExecutable(join(binDir, 'caddy'), '#!/bin/sh\nexit 0\n');
    await writeFakeSupervisorctl(binDir, statusPath, callsPath, { startingStatusChecks: 2 });

    const result = await execFileAsync('sh', [resolve(process.cwd(), 'plugins/scripts/vd-plugin-runtime-apply.sh')], {
      env: {
        ...process.env,
        PATH: `${binDir}:${process.env.PATH ?? ''}`,
        VD_PLUGIN_SUPERVISOR_CONFIG_DIR: supervisorConfigDir,
        VD_PLUGIN_SUPERVISOR_START_DELAY_SECONDS: '0',
      },
    });

    await expect(readFile(statusPath, 'utf8')).resolves.toBe('RUNNING\n');
    await expect(readFile(callsPath, 'utf8')).resolves.not.toContain('start vd-plugin--vd_beads_web--web');
    expect(result.stderr).toContain('Waiting for enabled plugin supervisor program vd-plugin--vd_beads_web--web to reach RUNNING');
  });

  it('fails with an actionable error when an enabled plugin program cannot be started', async () => {
    const tempRoot = await mkdtemp(join(tmpdir(), 'vd-plugin-runtime-apply-start-fails-'));
    const binDir = join(tempRoot, 'bin');
    const supervisorConfigDir = join(tempRoot, 'supervisor');
    const statusPath = join(tempRoot, 'supervisor-status');
    const callsPath = join(tempRoot, 'supervisor-calls');
    await mkdir(binDir);
    await mkdir(supervisorConfigDir);
    await writeFile(join(supervisorConfigDir, 'vd-plugin--vd_broken--web.conf'), [
      '; generated by VD plugin service orchestrator for vd.broken@v1 service web',
      '[program:vd-plugin--vd_broken--web]',
      'command=/bin/false',
      'autostart=true',
      '',
    ].join('\n'));
    await writeFile(statusPath, 'FATAL');
    await writeExecutable(join(binDir, 'node'), '#!/bin/sh\nexit 0\n');
    await writeExecutable(join(binDir, 'caddy'), '#!/bin/sh\nexit 0\n');
    await writeFakeSupervisorctl(binDir, statusPath, callsPath, { failStart: true });

    await expect(execFileAsync('sh', [resolve(process.cwd(), 'plugins/scripts/vd-plugin-runtime-apply.sh')], {
      env: {
        ...process.env,
        PATH: `${binDir}:${process.env.PATH ?? ''}`,
        VD_PLUGIN_SUPERVISOR_CONFIG_DIR: supervisorConfigDir,
      },
    })).rejects.toMatchObject({
      stderr: expect.stringContaining('Failed to start enabled plugin supervisor program vd-plugin--vd_broken--web'),
    });
  });

  it('retries Caddy reload until the admin endpoint is ready', async () => {
    const tempRoot = await mkdtemp(join(tmpdir(), 'vd-plugin-runtime-apply-'));
    const binDir = join(tempRoot, 'bin');
    const supervisorConfigDir = join(tempRoot, 'supervisor');
    const caddyCountPath = join(tempRoot, 'caddy-count');
    await mkdir(binDir);
    await mkdir(supervisorConfigDir);
    await writeExecutable(join(binDir, 'node'), '#!/bin/sh\nexit 0\n');
    await writeExecutable(join(binDir, 'supervisorctl'), '#!/bin/sh\nexit 0\n');
    await writeExecutable(join(binDir, 'caddy'), `#!/bin/sh
count="$(cat "$CADDY_COUNT_PATH" 2>/dev/null || echo 0)"
count=$((count + 1))
echo "$count" > "$CADDY_COUNT_PATH"
if [ "$count" -lt 3 ]; then
  exit 1
fi
exit 0
`);

    const result = await execFileAsync('sh', [resolve(process.cwd(), 'plugins/scripts/vd-plugin-runtime-apply.sh')], {
      env: {
        ...process.env,
        PATH: `${binDir}:${process.env.PATH ?? ''}`,
        CADDY_COUNT_PATH: caddyCountPath,
        VD_PLUGIN_SUPERVISOR_CONFIG_DIR: supervisorConfigDir,
        VD_PLUGIN_CADDY_RELOAD_ATTEMPTS: '3',
        VD_PLUGIN_CADDY_RELOAD_DELAY_SECONDS: '0',
      },
    });

    await expect(readFile(caddyCountPath, 'utf8')).resolves.toBe('3\n');
    expect(result.stderr).toContain('Caddy reload failed on attempt 1/3');
    expect(result.stderr).toContain('Caddy reload failed on attempt 2/3');
  });

  it('fails after bounded Caddy reload attempts when the admin endpoint never becomes ready', async () => {
    const tempRoot = await mkdtemp(join(tmpdir(), 'vd-plugin-runtime-apply-fails-'));
    const binDir = join(tempRoot, 'bin');
    const supervisorConfigDir = join(tempRoot, 'supervisor');
    const caddyCountPath = join(tempRoot, 'caddy-count');
    await mkdir(binDir);
    await mkdir(supervisorConfigDir);
    await writeExecutable(join(binDir, 'node'), '#!/bin/sh\nexit 0\n');
    await writeExecutable(join(binDir, 'supervisorctl'), '#!/bin/sh\nexit 0\n');
    await writeExecutable(join(binDir, 'caddy'), `#!/bin/sh
count="$(cat "$CADDY_COUNT_PATH" 2>/dev/null || echo 0)"
count=$((count + 1))
echo "$count" > "$CADDY_COUNT_PATH"
exit 1
`);

    await expect(execFileAsync('sh', [resolve(process.cwd(), 'plugins/scripts/vd-plugin-runtime-apply.sh')], {
      env: {
        ...process.env,
        PATH: `${binDir}:${process.env.PATH ?? ''}`,
        CADDY_COUNT_PATH: caddyCountPath,
        VD_PLUGIN_SUPERVISOR_CONFIG_DIR: supervisorConfigDir,
        VD_PLUGIN_CADDY_RELOAD_ATTEMPTS: '3',
        VD_PLUGIN_CADDY_RELOAD_DELAY_SECONDS: '0',
      },
    })).rejects.toMatchObject({
      stderr: expect.stringContaining('Caddy reload failed after 3 attempts; generated plugin config remains on disk'),
    });

    await expect(readFile(caddyCountPath, 'utf8')).resolves.toBe('3\n');
  });
});

async function writeExecutable(path: string, content: string): Promise<void> {
  await writeFile(path, content, { mode: 0o755 });
  await chmod(path, 0o755);
}

async function writeFakeSupervisorctl(
  binDir: string,
  statusPath: string,
  callsPath: string,
  options: { failStart?: boolean; nonZeroStatuses?: string[]; startingStatusChecks?: number } = {},
): Promise<void> {
  await writeExecutable(join(binDir, 'supervisorctl'), `#!/bin/sh
echo "$*" >> "${callsPath}"
case "$1" in
  reread|update)
    exit 0
    ;;
  status)
    status="$(cat "${statusPath}")"
    if [ "$status" = "STARTING" ] && [ "${options.startingStatusChecks ?? 0}" -gt 0 ]; then
      count_path="${statusPath}.status-count"
      count="$(cat "$count_path" 2>/dev/null || echo 0)"
      count=$((count + 1))
      echo "$count" > "$count_path"
      if [ "$count" -ge "${options.startingStatusChecks ?? 0}" ]; then
        echo RUNNING > "${statusPath}"
        status=RUNNING
      fi
    fi
    echo "$2 $status"
    case " ${options.nonZeroStatuses?.join(' ') ?? ''} " in
      *" $status "*)
        exit 3
        ;;
    esac
    exit 0
    ;;
  start)
    if [ "${options.failStart ? 'true' : 'false'}" = "true" ]; then
      echo "failed to start $2" >&2
      exit 1
    fi
    echo RUNNING > "${statusPath}"
    echo "$2: started"
    exit 0
    ;;
esac
exit 1
`);
}
